### ISSUE TITLE
Add page to gliders.ioos.us for EGO workshop

### ISSUE THREAD

**Issue by Bobfrat** [ioos/ioos-us#198]
We need to set up a sub-page on the https://gliders.ioos.us webpage for the upcoming Glider meeting in May. I would like to do something similar to what is done [here](https://usclivar.org/meetings/sources-and-sinks-ocean-mesoscale-eddy-energy).  Just a page we can point people too with information about the event and links to the flyer, call for abstract, and schedule once its finalized.

**Comment by Bobfrat** [comment]
Need to know the subfolder we'll use, for example gliders.ioos.us/conferences or more specifically gliders.ioos.us/ego_2019.

Content to be provided by Ben LaCour.

**Comment by benito334** [comment]
How about gliders.ioos.us/UG2_EGO_2019

**Comment by Bobfrat** [comment]
Looks like there is a link to the meeting PDF here btw:
https://gliders.ioos.us/meetingsevents/

**Comment by gitchrisadams** [comment]
@benito334 I have initial page setup and can be viewed:
https://gliders.ioos.us/ug2_ego_2019/
Let me know if you would like any specific changes and what content needs to be added.
Thanks.

**Comment by benito334** [comment]
> @benito334 I have initial page setup and can be viewed:
> https://gliders.ioos.us/ug2_ego_2019/
> Let me know if you would like any specific changes and what content needs to be added.
> Thanks.

This is perfect thanks. I'll add some content and let you know if I need any help.

**Comment by benito334** [comment]
@gitchrisadams 
Is it possible to replace the menu with a side banner such as what is shown [here](https://usclivar.org/meetings/sources-and-sinks-ocean-mesoscale-eddy-energy)? Something I can add more than just page links to. Maybe put the "Meeting Menu" first followed by the "Dead Lines" and then Schedule.

**Comment by gitchrisadams** [comment]
@benito334 I'll work on adding a side banner instead of siderbar nav let you know what I come up with. I'll keep that order in mind when working on this.

**Comment by benito334** [comment]
@gitchrisadams Thanks this is great. Am I able to add the widget so I can edit the text as due dates pass etc.?

**Comment by gitchrisadams** [comment]
@benito334  Yes, I'm in the middle of some edits so can you hold of editing any pages for now. I also placed some comments in the code for where the Feedback button code is located. Try not to remove that unless you do not want the Feedback button. 
I'll post some screenshots of where the custom html widget is located and some more info how to update it.

**Comment by benito334** [comment]
@gitchrisadams Awesome thanks so much. I'll hold off on doing anything until you tell me. One thing I noticed is the formatting on the bottom of the logistics page seems off. I'm not sure how to fix this. Thanks again for the fast work! Its really appreciated.

**Comment by gitchrisadams** [comment]
I noticed that about the Logistics page, I'm going to fix that too.

**Comment by gitchrisadams** [comment]
@benito334 
I finished editing the logistics page, let me know what you think.
https://gliders.ioos.us/ug2_ego_2019_logistics/

**Information for editing pages:**
**Editing the sidebar:**
From the left side menu in wordpress if you go to:
Appearance > widgets
There is a widget called Widgets for Shortcodes.
There is a custom widget on the right called "Meeting Menu"
![image](https://user-images.githubusercontent.com/9978238/51746112-13fa2800-2073-11e9-8b81-1ab238361187.png)
This is where html can be edited to change the sidebar.

**Customizing the CSS for pages:**
Go to Appearance > Customize > Additional CSS
You will see some comments about the UG2 Page.
This section can be edited or more css added to customize the individual pages or sidebar.

**Additional info:**
Be careful changing css since when you save it makes the code live instantly, so might be good to test live page as soon as you update to confirm updating css did not break anything.
Before making a page live you can click preview to ensure it displays properly before saving and going live.
You will see comments in the pages for the Feedback menu, be careful not to edit this code.
Keep in mind that the col-8 divs and row divs have to do with how the sidebar and main content are laid out on the page. If these are changed or closing divs are deleted, it will affect how the content displays. 

Any questions, let me know.

**Comment by benito334** [comment]
@gitchrisadams Thanks so much! Wordpress is kicking my butt. For some reason I can't get the customizer to load and I don't know html or css. I made most of my text edits and have a few small tweaks with formatting and a new graphic that is being made. I'll probably need your help making those changes when I have them. I'll let you know.

**Comment by gitchrisadams** [comment]
@benito334 No problem. Once you have the changes, just post on here and I'll take a look.

**Comment by benito334** [comment]
Images
Replace bottom “Supported By” banner with the 4 logos I added to the media folder.
Including text that says “Supported By”. 

Home page: Move image clipped from flyer to the top of the page and center it over the side banner and content. This will be replaced with a wide graphic similar to this one but larger.
![image](https://user-images.githubusercontent.com/33009334/51755962-d951b900-208d-11e9-8a83-49b0118914c3.png)


**Lower Priority Edits**
Some text that isn’t hyper linked appears to be hyperlinked? At one point in editing text I hit clear formatting for one text element. I’m not sure if that did it. 

Home Page: Meeting Overview & Goal>  “The European” 
Side Banner: Schedule> “Agenda coming soon!”
		RSVP> “If you are….”
Logistics: Event Venue> “The Meeting will take place at”

Formatting
Side Banner: Deadlines> Align “Submit Abstracts Here” to the left and add a line space after it to separate it more from the Schedule section

Home: Breakout Session> Reduce space between each of the three sections and reduce the title (Glider Best Practices, Capacity….) text size a hair.

**Comment by gitchrisadams** [comment]
@benito334 I'll look into getting these updates. Probably will get to these Monday.

**Comment by gitchrisadams** [comment]
@benito334 Take a look at https://gliders.ioos.us/ug2_ego_2019
And let me know of those changes look o.k. I addressed all the changes in issue above.
For the logos at the bottom, If you want them to link to corresponding websites, just me know and I'll link them up.
If you edit any of the html documents directly/html can you just test the feedback button on the left side and ensure it is still functional before updating/saving.
Let me know if you need anything else.

**Comment by benito334** [comment]
@gitchrisadams Thanks all looks good. I should only be editing text from here on. I'll avoid making changes to html.
