### ISSUE TITLE
ATN website text updates

### ISSUE THREAD

**Issue by thcurtis** [ioos/ioos-us#265]
Please replace/update the text on ATN webpages as provided in the attached document (url's identified above each section in the document). Also link the attached PDF where indicated. Please ensure that Bill Woodward's (retired) name and contact info is removed from the website. Contact me with any questions. 

[ATN ioos.us website update Mar2023.docx](https://github.com/ioos/ioos-us/files/11022728/ATN.ioos.us.website.update.Mar2023.docx)
[atn_argos_request_2023.pdf](https://github.com/ioos/ioos-us/files/11022729/atn_argos_request_2023.pdf)

Thank you!
~~Tobey

**Comment by MathewBiddle** [comment]
@mwengren any ideas?

**Comment by MathewBiddle** [comment]
Found the source repo: https://github.com/ioos/atn-docs/tree/master

**Comment by mwengren** [comment]
Hey @MathewBiddle I think the issue as to why this hasn't moved is that it was added to the ioos.us 'homepage' repo and not the individual repo where the code lives, as you found.

We have some docs (internal links below) that are supposed to be resources for IOOS folks to know what to do to make changes like this happen, but they probably need some updating (for one, we linked to the atn-dac repo rather than atn-docs in those, it looks like, that should be fixed).

- [Trello card](https://trello.com/c/uwY2XIyN/154-ioosus-site-management-process)
- [Google doc](https://docs.google.com/document/d/1WXYTKOUCtgazQDoWPhVrSxif4Cn3IShgzvyN23S9gJ4/edit#)
- [Site/repo spreadsheet](https://docs.google.com/spreadsheets/d/1AoFLJUJZiDiXpI3Da-57CZQhgle59kGwrzhkCYSG5Ho/edit#gid=0)

If this issue were ported over to that repo, Axiom should pick it up.  

The Trello card and Google Doc are more geared towards major changes I think - not more minor fixes like this appears to be.  We could update those to reflect that not everything needs to go through a review process by Ops necessarily, just a resource to quickly find where to go to put in a change request for a particular ioos.us sub-site.

**Comment by MathewBiddle** [comment]
Thanks, @mwengren! I'll close this issue in favor of atn-docs. The biggest trouble here was finding the right place to log the issue. 

Maybe we should have a requirement that all ioos.us websites include a link back to their source GH repo? If it exists.

**Comment by mwengren** [comment]
FWIW, I updated the Trello card with some new details and copied the spreadsheet to the IOOS-owned google drive.  We should work on updating the resources linked from the Trello card with clearer instructions if need be.
